### ISSUE TITLE
revC1 schematic : lvds compatible connector part number is incorrect

### ISSUE THREAD

**Issue by TomKeddie** [GlasgowEmbedded/glasgow#172]
The suggested part number 20021321-00040T4LF in the schematic refers to a 40 pin connector, a 44 pin connector is required.  Unfortunately I could not find an economic 44 pin connector to recommend.

![image](https://user-images.githubusercontent.com/4367175/68098215-50fc1200-fe70-11e9-9961-b380c65d59a8.png)

**Comment by electroniceel** [comment]
For J5 itself, @esden has used Samtec FTSH-122-01-F-DV-K-P while @gregdavill has used FTS-122-01-L-DV.

According to the mating connector search at Samtec, CLP-122-02-F-D and FLE-122-01-G-DV should be possible mating connectors. Both seem to be available in single quantity at Mouser.

But I guess we should try both and check if the mechanics work out, meaning they stay on, but can still be removed without too much stress on the solder joints of J5.

**Comment by electroniceel** [comment]
I now tested Samtec FLE-122-01-G-DV-A and CLP-122-02-F-D-A on the FTS-122-01-L-DV of my Glasgow:

- Both fit
- Both are availably in small quantities from Mouser
- The CLP one is more difficult to insert and remove, Samtec probably increased the tension due to the smaller height
- The FLE one looks and feels more sturdy to me

-> I would recommend the Samtec FLE-122-01-G-DV-A in the schematics
